name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:15-3.3
        env:
          POSTGRES_USER: geofence
          POSTGRES_PASSWORD: geofence
          POSTGRES_DB: geofence
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -h localhost -p 5432 -U geofence"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi

      - name: Wait for Postgres
        run: |
          echo "Waiting for postgres to be ready..."
          for i in {1..60}; do
            if pg_isready -h localhost -p 5432 -U geofence; then
              echo "Postgres is ready" && break
            fi
            sleep 1
          done

      - name: Run alembic migrations
        env:
          DATABASE_URL: postgresql+psycopg2://geofence:geofence@localhost:5432/geofence
          POSTGRES_HOST: localhost
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m alembic upgrade head

      - name: Run tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: geofence
          POSTGRES_USER: geofence
          POSTGRES_PASSWORD: geofence
          PYTHONPATH: ${{ github.workspace }}
          E2E_DB_WAIT: 300
        run: |
          python -m pytest -q
